# Generated by Django 4.0.3 on 2022-03-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nac',
            field=models.CharField(max_length=50),
        ),
    ]
