# Generated by Django 4.0.3 on 2022-03-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaApp', '0002_alter_persona_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dui',
            field=models.CharField(max_length=100),
        ),
    ]
